language: python
# Whitelisting master
branches:
  only:
    - master
git:
  depth: 10
python:
  - "3.5"
before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - df -h
  - date
  - pwd
  - uname -m
  - python -V
  - git --version
  - git tag
  - apt-get build-dep -qq python3-numpy python3-scipy python3-matplotlib
  - virtualenv venv --system-site-packages
install:
  - echo "install start"
  - activate venv
  - pip install seaborn
before_script:
  - echo "before_script"
script:
  cd assignment1
  python -m py.test tests/