language: python
sudo: false
# Whitelisting master
branches:
  only:
    - master
git:
  depth: 10
python:
  - "3.5"
before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - df -h
  - date
  - pwd
  - uname -m
  - python -V
  - git --version
  - git tag
  - pip install wheel atlas numpy scipy matplotlib
install:
  - echo "install start"
  - pip install seaborn
before_script:
  - echo "before_script"
script:
  cd assignment1
  python -m py.test tests/